vye:
  # NOTE: This is a fake key for testing purposes only.
  ivr_key: 'testing-vye-ivr-key'
  scrypt:
    # NOTE: This is a random salt for testing purposes only.
    salt: 'testing-vye-scrypt-salt'
    N: 8
    r: 8
    p: 1
    length: 16
